[metadata]
name = trisul_ai_cli
version = 1.0.0
description = Trisul AI CLI that starts a local MCP server and a client.
long_description = file: README.md
long_description_content_type = text/markdown
author = Parthasarathy B
author-email = partha@unleashnetworks.com
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.10
include_package_data = True
install_requires =
    nest_asyncio
    mcp
    chromadb
    pyzmq
    protobuf
    matplotlib
    python-dotenv
    reportlab
    openpyxl
    stdiomask
    langchain>=1.1
    langchain-core>=1.1.2
    langchain-google-genai>=4.0.0
    langchain-openai>=1.0
    langchain-anthropic>=1.0
    langchain-voyageai>=0.4.1
    aiohttp>=3.10
    voyageai
    fastapi
    uvicorn[standard]

[options.packages.find]
where = .


[options.package_data]
trisul_ai_cli =
    chroma_store/*
    chroma_store/**/*
    trisul_ai_memory.json
    assets/*
    assets/**/*
    prompts/*
    resources/*.json

[options.entry_points]
console_scripts =
    trisul_ai_cli = trisul_ai_cli.cli:cli_main


